language: ruby
rvm:
  - 2.2.1

bundler_args: --without development production

script:
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "IH4rv7KuM4hyLlfdyEKGDcPCOoH5mohIbBFjHhYJxwxf3O2jtAdddhWwy1rXwh9TjcYk/sKJWds2i7x6Eg5vZmjR8gLiMTYyTuMl16EW5Vp9USQz1bV5jrdC0JcADmHIIPrA7fCup3FtItlics+iDy9fmPiOjXxbmAWzQDCo/WA="
  app:
    master: scholarmap-preview
  on:
    repo: chrisvfritz/scholarmap_visualization