language: ruby
rvm:
  - 2.2.0

addons:
  code_climate:
    repo_token:
      secure: "CF0eJeG/TQf7P19m/sydNBAnI+ciskFNVemAljZ8WmFsfhkx5hVNCbNvk2zutSvrjOPxuefMZQWinBxd/FZyP99tlJQsasnZBpjH8Sz5qGwRCY4ILmXYuKGk+fbGVYGBAaQ6pluKN6gR+Kz9uXEawMsNtE2vzLh+jJwriM6+pHs="

bundler_args: --without development production

script:
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "CHUfTQfUMMJzDGe1MElInBW2cGTkkm32n00MPiLSCDVl58TBBsVN3cfzx/74ZJKyzwhx2KbNikQPa6UXlnugGHGQOH0Da0ujw/V2fC9Tp2bAuNLyW6a1zzordIEBdaxPXGR71biwSizU4dXp1iKWvzAc+ivEuSYLjme1CO9rG0U="
  app:
    master: scholarmap-preview
  on:
    repo: chrisvfritz/scholarmap_visualization